import dns from 'node:dns';
dns.setServers(['1.1.1.1', '8.8.4.4']);

import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from 'react-toastify';


const OutfitFont = Outfit({
    subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto w-full">
        
          {children}
        </main>
        <ToastContainer />
        <Footer></Footer>
        </body>
    </html>
  );
}
